In [12]:
import pandas as pd 
import numpy as np
plt.style.use('dark_background')
from matplotlib import pyplot as plt 
import seaborn as sns
plt.style.use('ggplot')

1.Створіть одновимірний масив (вектор) з першими 20-ма натуральними числами та виведіть його значення.

In [3]:
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Створіть двовимірний масив (матрицю) розміром 4x4, заповніть його одиницями та виведіть його значення.

In [9]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від -1 до 1 та виведіть його значення.

In [10]:
np.random.uniform(-1, 1, (5, 5))

array([[-0.52710184,  0.60640684,  0.0851919 ,  0.95476549,  0.55336296],
       [ 0.17300209, -0.21309516, -0.95336935, -0.53199051, -0.8931811 ],
       [-0.42031567,  0.91368018, -0.29667016, -0.59237856,  0.9528351 ],
       [-0.94951544, -0.62802671,  0.16584233, -0.70696838,  0.96303463],
       [ 0.89020034, -0.1670702 ,  0.94670434, -0.54599376,  0.05174231]])

Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [11]:
np.random.uniform(0,1,(3,3))

array([[0.61039263, 0.88684154, 0.68396373],
       [0.93806482, 0.50004286, 0.53518961],
       [0.44261991, 0.70677829, 0.4933134 ]])

Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в діапазоні від 1 до 20 та виконайте на них поелементні операції додавання, віднімання та множення

In [37]:
vector_1 = np.random.randint(1, 21, 6)

In [39]:
vector_2 =np.random.randint(1, 21, 6)

In [40]:
vector_1 + vector_2

array([20, 14, 25, 29, 20, 22])

In [41]:
vector_1 - vector_2

array([ -8,   6,   5,  -5,   8, -14])

In [42]:
vector_1 * vector_2

array([ 84,  40, 150, 204,  84,  72])

Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.

In [46]:
matr_1 = np.random.randint(1,6,(3,2))

In [47]:
matr_2 = np.random.randint(1,6,(2,4))

In [50]:
np.dot(matr_1,matr_2)

array([[24, 15, 21, 18],
       [24,  9, 19, 26],
       [24, 18, 22, 14]])

Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [53]:
transposed_matrix = np.random.uniform(0,1, (3,3))

In [54]:
np.transpose(transposed_matrix)

array([[0.19590857, 0.40870071, 0.36089604],
       [0.89582214, 0.33923937, 0.32508059],
       [0.31869756, 0.02262181, 0.81257683]])

Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [61]:
first_matrix = np.random.randint(1,11,(3,3))

In [62]:
second_matrix = np.random.randint(1,11,(3,3))

In [63]:
first_matrix - second_matrix

array([[ 3, -1, -2],
       [ 9, -1,  0],
       [ 5, -7, -1]])

Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від -5 до 5 та знайдіть їх добуток.

In [65]:
np.random.randint(-5,5, (3,3)) * np.random.randint(-5,5, (3,3))

array([[ -6, -10,   0],
       [-20,   0,   0],
       [  0,   0,   1]])

Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [6]:
matrix = np.random.uniform(-1, 1, (3, 3))

In [7]:
np.sum(matrix, axis=1)

array([-0.95449704,  0.82593771, -0.42627587])

# За допомогою метода  read_html  скачати дані з  таблиці "Коефіцієнт народжуваності в регіонах України (1950—2014)" за посиланням

# Відобразити перші 10 рядків таблиці за допомогою методу head

In [5]:
df = pd.read_html('https://uk.wikipedia.org/wiki/%D0%9D%D0%B0%D1%80%D0%BE%D0%B4%D0%B6%D1%83%D0%B2%D0%B0%D0%BD%D1%96%D1%81%D1%82%D1%8C_%D0%B2_%D0%A3%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D1%96')

In [6]:
df = df[20].copy()

In [7]:
df.head(10)

,регіон,1950,1960,1970,1990,1992,1994,1996,2000,2004,2008,2012,2014
0,Автономна Республіка Крим,230.0,206.0,160.0,130,109,93,80,73,90,119,126,NaN
1,Вінницька область,224.0,192.0,142.0,124,119,107,103,84,90,108,112,109.0
2,Волинська область,247.0,250.0,179.0,153,150,137,125,112,119,148,148,141.0
3,Дніпропетровська область,204.0,204.0,151.0,123,106,92,80,71,89,110,112,111.0
4,Донецька область,271.0,214.0,140.0,109,94,82,70,61,76,98,98,82.0
5,Житомирська область,261.0,223.0,159.0,129,128,118,108,89,98,113,122,120.0
6,Закарпатська область,314.0,273.0,207.0,168,161,138,128,115,124,147,151,146.0
7,Запорізька область,219.0,197.0,150.0,124,107,92,81,71,85,103,106,106.0
8,Івано-Франківська область,243.0,248.0,182.0,155,144,131,122,103,107,123,124,122.0
9,Київська область,204.0,189.0,156.0,123,111,99,92,73,90,117,122,121.0

# Визначити кількість рядків і стовпців в датафрейме (метод shape)

In [52]:
df.shape

(28, 13)

In [54]:
df.dtypes

регіон     object
1950      float64
1960      float64
1970      float64
1990        int64
1992        int64
1994        int64
1996        int64
2000        int64
2004        int64
2008        int64
2012        int64
2014      float64
dtype: object

# Замініть значення "—" в таблиці значеннями NaN

In [62]:
# можемо побачити, що NaN розставлені автоматично замість -

In [82]:
df.astype({'1950':np.float}).head()

C:\Users\tuf\AppData\Local\Temp\ipykernel_10180\4179551072.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  df.astype({'1950':np.float}).head()

,регіон,1950,1960,1970,1990,1992,1994,1996,2000,2004,2008,2012,2014
0,Автономна Республіка Крим,230.0,206.0,160.0,130,109,93,80,73,90,119,126,NaN
1,Вінницька область,224.0,192.0,142.0,124,119,107,103,84,90,108,112,109.0
2,Волинська область,247.0,250.0,179.0,153,150,137,125,112,119,148,148,141.0
3,Дніпропетровська область,204.0,204.0,151.0,123,106,92,80,71,89,110,112,111.0
4,Донецька область,271.0,214.0,140.0,109,94,82,70,61,76,98,98,82.0

In [ ]:
ми можемо побачити в датафреймі немає строкових типів даних, вони float aбо int

# Обчислити, скільки проміжків у кожному стовпці (використовуйте методи isnull, sum та len)

In [84]:
df.isnull().sum()

регіон    0
1950      2
1960      1
1970      1
1990      0
1992      0
1994      0
1996      0
2000      0
2004      0
2008      0
2012      0
2014      2
dtype: int64

In [88]:
df.isnull().mean() #-  рахую пропущені значення,  ставлячи середне значення, щоб одразу можно було дивитись значення у процентах

регіон    0.000000
1950      0.071429
1960      0.035714
1970      0.035714
1990      0.000000
1992      0.000000
1994      0.000000
1996      0.000000
2000      0.000000
2004      0.000000
2008      0.000000
2012      0.000000
2014      0.071429
dtype: float64

In [90]:
df

,регіон,1950,1960,1970,1990,1992,1994,1996,2000,2004,2008,2012,2014
0,Автономна Республіка Крим,230.0,206.0,160.0,130,109,93,80,73,90,119,126,NaN
1,Вінницька область,224.0,192.0,142.0,124,119,107,103,84,90,108,112,109.0
2,Волинська область,247.0,250.0,179.0,153,150,137,125,112,119,148,148,141.0
3,Дніпропетровська область,204.0,204.0,151.0,123,106,92,80,71,89,110,112,111.0
4,Донецька область,271.0,214.0,140.0,109,94,82,70,61,76,98,98,82.0
5,Житомирська область,261.0,223.0,159.0,129,128,118,108,89,98,113,122,120.0
6,Закарпатська область,314.0,273.0,207.0,168,161,138,128,115,124,147,151,146.0
7,Запорізька область,219.0,197.0,150.0,124,107,92,81,71,85,103,106,106.0
8,Івано-Франківська область,243.0,248.0,182.0,155,144,131,122,103,107,123,124,122.0
9,Київська область,204.0,189.0,156.0,123,111,99,92,73,90,117,122,121.0
10,Кіровоградська область,216.0,171.0,145.0,126,119,107,96,79,86,102,110,108.0
11,Луганська область,262.0,235.0,144.0,116,101,84,72,62,73,95,96,51.0
12,Львівська область,234.0,240.0,171.0,140,132,117,111,91,101,113,119,119.0
13,Миколаївська область,211.0,194.0,155.0,137,123,107,96,80,90,112,115,112.0
14,Одеська область,241.0,192.0,148.0,126,114,100,92,80,96,120,127,123.0
15,Полтавська область,186.0,163.0,131.0,118,108,95,88,70,75,97,99,100.0
16,Рівненська область,269.0,267.0,193.0,158,154,145,132,118,125,148,159,148.0
17,Сумська область,216.0,184.0,132.0,115,105,92,84,70,72,91,97,92.0
18,Тернопільська область,213.0,216.0,157.0,142,138,123,115,92,99,113,113,109.0
19,Харківська область,197.0,173.0,140.0,114,98,83,76,68,80,98,99,101.0
20,Херсонська область,208.0,214.0,166.0,143,130,111,98,85,91,113,117,115.0
21,Хмельницька область,234.0,198.0,148.0,129,124,111,106,85,91,110,113,112.0
22,Черкаська область,205.0,179.0,144.0,123,114,100,93,75,77,95,100,98.0
23,Чернівецька область,247.0,218.0,170.0,148,140,128,121,101,106,122,128,129.0
24,Чернігівська область,220.0,183.0,127.0,108,98,88,82,69,75,89,94,90.0
25,Київ,NaN,174.0,159.0,120,97,81,76,73,98,116,120,121.0
26,Севастополь (міськрада),NaN,NaN,NaN,125,96,76,69,70,97,110,120,NaN
27,Україна,228.0,205.0,152.0,126,114,100,92,78,90,110,114,108.0

# Видалити дані для всієї країни з таблиці в останньому рядку таблиці

In [96]:
df.reset_index(drop=True)

,регіон,1950,1960,1970,1990,1992,1994,1996,2000,2004,2008,2012,2014
0,Автономна Республіка Крим,230.0,206.0,160.0,130,109,93,80,73,90,119,126,NaN
1,Вінницька область,224.0,192.0,142.0,124,119,107,103,84,90,108,112,109.0
2,Волинська область,247.0,250.0,179.0,153,150,137,125,112,119,148,148,141.0
3,Дніпропетровська область,204.0,204.0,151.0,123,106,92,80,71,89,110,112,111.0
4,Донецька область,271.0,214.0,140.0,109,94,82,70,61,76,98,98,82.0
5,Житомирська область,261.0,223.0,159.0,129,128,118,108,89,98,113,122,120.0
6,Закарпатська область,314.0,273.0,207.0,168,161,138,128,115,124,147,151,146.0
7,Запорізька область,219.0,197.0,150.0,124,107,92,81,71,85,103,106,106.0
8,Івано-Франківська область,243.0,248.0,182.0,155,144,131,122,103,107,123,124,122.0
9,Київська область,204.0,189.0,156.0,123,111,99,92,73,90,117,122,121.0
10,Кіровоградська область,216.0,171.0,145.0,126,119,107,96,79,86,102,110,108.0
11,Луганська область,262.0,235.0,144.0,116,101,84,72,62,73,95,96,51.0
12,Львівська область,234.0,240.0,171.0,140,132,117,111,91,101,113,119,119.0
13,Миколаївська область,211.0,194.0,155.0,137,123,107,96,80,90,112,115,112.0
14,Одеська область,241.0,192.0,148.0,126,114,100,92,80,96,120,127,123.0
15,Полтавська область,186.0,163.0,131.0,118,108,95,88,70,75,97,99,100.0
16,Рівненська область,269.0,267.0,193.0,158,154,145,132,118,125,148,159,148.0
17,Сумська область,216.0,184.0,132.0,115,105,92,84,70,72,91,97,92.0
18,Тернопільська область,213.0,216.0,157.0,142,138,123,115,92,99,113,113,109.0
19,Харківська область,197.0,173.0,140.0,114,98,83,76,68,80,98,99,101.0
20,Херсонська область,208.0,214.0,166.0,143,130,111,98,85,91,113,117,115.0
21,Хмельницька область,234.0,198.0,148.0,129,124,111,106,85,91,110,113,112.0
22,Черкаська область,205.0,179.0,144.0,123,114,100,93,75,77,95,100,98.0
23,Чернівецька область,247.0,218.0,170.0,148,140,128,121,101,106,122,128,129.0
24,Чернігівська область,220.0,183.0,127.0,108,98,88,82,69,75,89,94,90.0
25,Київ,NaN,174.0,159.0,120,97,81,76,73,98,116,120,121.0
26,Севастополь (міськрада),NaN,NaN,NaN,125,96,76,69,70,97,110,120,NaN
27,Україна,228.0,205.0,152.0,126,114,100,92,78,90,110,114,108.0

In [98]:
df.drop(index = 27, inplace=True)

In [102]:
df.shape

(27, 13)

# Замінити пропущені дані у стовпцях середніми значеннями за стовпчиком  (метод fillna)

In [104]:
df.fillna(df.mean(), inplace=True)

C:\Users\tuf\AppData\Local\Temp\ipykernel_10180\820435583.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.fillna(df.mean(), inplace=True)

In [106]:
df.head()

,регіон,1950,1960,1970,1990,1992,1994,1996,2000,2004,2008,2012,2014
0,Автономна Республіка Крим,230.0,206.0,160.0,130,109,93,80,73,90,119,126,111.44
1,Вінницька область,224.0,192.0,142.0,124,119,107,103,84,90,108,112,109.00
2,Волинська область,247.0,250.0,179.0,153,150,137,125,112,119,148,148,141.00
3,Дніпропетровська область,204.0,204.0,151.0,123,106,92,80,71,89,110,112,111.00
4,Донецька область,271.0,214.0,140.0,109,94,82,70,61,76,98,98,82.00

In [107]:
df

,регіон,1950,1960,1970,1990,1992,1994,1996,2000,2004,2008,2012,2014
0,Автономна Республіка Крим,230.00,206.000000,160.0,130,109,93,80,73,90,119,126,111.44
1,Вінницька область,224.00,192.000000,142.0,124,119,107,103,84,90,108,112,109.00
2,Волинська область,247.00,250.000000,179.0,153,150,137,125,112,119,148,148,141.00
3,Дніпропетровська область,204.00,204.000000,151.0,123,106,92,80,71,89,110,112,111.00
4,Донецька область,271.00,214.000000,140.0,109,94,82,70,61,76,98,98,82.00
5,Житомирська область,261.00,223.000000,159.0,129,128,118,108,89,98,113,122,120.00
6,Закарпатська область,314.00,273.000000,207.0,168,161,138,128,115,124,147,151,146.00
7,Запорізька область,219.00,197.000000,150.0,124,107,92,81,71,85,103,106,106.00
8,Івано-Франківська область,243.00,248.000000,182.0,155,144,131,122,103,107,123,124,122.00
9,Київська область,204.00,189.000000,156.0,123,111,99,92,73,90,117,122,121.00
10,Кіровоградська область,216.00,171.000000,145.0,126,119,107,96,79,86,102,110,108.00
11,Луганська область,262.00,235.000000,144.0,116,101,84,72,62,73,95,96,51.00
12,Львівська область,234.00,240.000000,171.0,140,132,117,111,91,101,113,119,119.00
13,Миколаївська область,211.00,194.000000,155.0,137,123,107,96,80,90,112,115,112.00
14,Одеська область,241.00,192.000000,148.0,126,114,100,92,80,96,120,127,123.00
15,Полтавська область,186.00,163.000000,131.0,118,108,95,88,70,75,97,99,100.00
16,Рівненська область,269.00,267.000000,193.0,158,154,145,132,118,125,148,159,148.00
17,Сумська область,216.00,184.000000,132.0,115,105,92,84,70,72,91,97,92.00
18,Тернопільська область,213.00,216.000000,157.0,142,138,123,115,92,99,113,113,109.00
19,Харківська область,197.00,173.000000,140.0,114,98,83,76,68,80,98,99,101.00
20,Херсонська область,208.00,214.000000,166.0,143,130,111,98,85,91,113,117,115.00
21,Хмельницька область,234.00,198.000000,148.0,129,124,111,106,85,91,110,113,112.00
22,Черкаська область,205.00,179.000000,144.0,123,114,100,93,75,77,95,100,98.00
23,Чернівецька область,247.00,218.000000,170.0,148,140,128,121,101,106,122,128,129.00
24,Чернігівська область,220.00,183.000000,127.0,108,98,88,82,69,75,89,94,90.00
25,Київ,231.04,174.000000,159.0,120,97,81,76,73,98,116,120,121.00
26,Севастополь (міськрада),231.04,207.576923,156.0,125,96,76,69,70,97,110,120,111.44

In [111]:
df
df.fillna(df.mean(), inplace=True)

C:\Users\tuf\AppData\Local\Temp\ipykernel_10180\1440900962.py:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.fillna(df.mean(), inplace=True)

In [115]:
df.drop(index=27, inplace = True)

# Отримайте список регіонів, де народжуваність у 2014 році була вищою за середню по Україні

In [127]:
avg = df['2014'].mean() #видаляємо останні індекси, щоб прибрати загальний коєфіцієнт

In [130]:
df[df['2014'] > avg]

,регіон,1950,1960,1970,1990,1992,1994,1996,2000,2004,2008,2012,2014
2,Волинська область,247.000000,250.0,179.0,153,150,137,125,112,119,148,148,141.0
5,Житомирська область,261.000000,223.0,159.0,129,128,118,108,89,98,113,122,120.0
6,Закарпатська область,314.000000,273.0,207.0,168,161,138,128,115,124,147,151,146.0
8,Івано-Франківська область,243.000000,248.0,182.0,155,144,131,122,103,107,123,124,122.0
9,Київська область,204.000000,189.0,156.0,123,111,99,92,73,90,117,122,121.0
12,Львівська область,234.000000,240.0,171.0,140,132,117,111,91,101,113,119,119.0
13,Миколаївська область,211.000000,194.0,155.0,137,123,107,96,80,90,112,115,112.0
14,Одеська область,241.000000,192.0,148.0,126,114,100,92,80,96,120,127,123.0
16,Рівненська область,269.000000,267.0,193.0,158,154,145,132,118,125,148,159,148.0
20,Херсонська область,208.000000,214.0,166.0,143,130,111,98,85,91,113,117,115.0
21,Хмельницька область,234.000000,198.0,148.0,129,124,111,106,85,91,110,113,112.0
23,Чернівецька область,247.000000,218.0,170.0,148,140,128,121,101,106,122,128,129.0
25,Київ,230.923077,174.0,159.0,120,97,81,76,73,98,116,120,121.0

In [131]:
med = df['2014'].median()

In [136]:
df[df['2014'] > med]

,регіон,1950,1960,1970,1990,1992,1994,1996,2000,2004,2008,2012,2014
2,Волинська область,247.000000,250.0,179.0,153,150,137,125,112,119,148,148,141.0
5,Житомирська область,261.000000,223.0,159.0,129,128,118,108,89,98,113,122,120.0
6,Закарпатська область,314.000000,273.0,207.0,168,161,138,128,115,124,147,151,146.0
8,Івано-Франківська область,243.000000,248.0,182.0,155,144,131,122,103,107,123,124,122.0
9,Київська область,204.000000,189.0,156.0,123,111,99,92,73,90,117,122,121.0
12,Львівська область,234.000000,240.0,171.0,140,132,117,111,91,101,113,119,119.0
13,Миколаївська область,211.000000,194.0,155.0,137,123,107,96,80,90,112,115,112.0
14,Одеська область,241.000000,192.0,148.0,126,114,100,92,80,96,120,127,123.0
16,Рівненська область,269.000000,267.0,193.0,158,154,145,132,118,125,148,159,148.0
20,Херсонська область,208.000000,214.0,166.0,143,130,111,98,85,91,113,117,115.0
21,Хмельницька область,234.000000,198.0,148.0,129,124,111,106,85,91,110,113,112.0
23,Чернівецька область,247.000000,218.0,170.0,148,140,128,121,101,106,122,128,129.0
25,Київ,230.923077,174.0,159.0,120,97,81,76,73,98,116,120,121.0

# В якому регіоні була найвища народжуваність у 2010 та 2012 роках (окремо).

In [148]:
df[['регіон','2012']].groupby('регіон').agg({'2012':'sum'}).sort_values('2012',ascending = False).head()

                      2012
регіон
Рівненська область     159
Закарпатська область   151
Волинська область      148
Чернівецька область    128
Одеська область        127

In [160]:
top_2014 = data = df[['регіон','2014']].sort_values('2014',ascending = False)

In [161]:
top_2014

                       регіон        2014
16         Рівненська область  148.000000
6        Закарпатська область  146.000000
2           Волинська область  141.000000
23        Чернівецька область  129.000000
14            Одеська область  123.000000
8   Івано-Франківська область  122.000000
25                       Київ  121.000000
9            Київська область  121.000000
5         Житомирська область  120.000000
12          Львівська область  119.000000
20         Херсонська область  115.000000
13       Миколаївська область  112.000000
21        Хмельницька область  112.000000
0   Автономна Республіка Крим  111.307692
26    Севастополь (міськрада)  111.307692
3    Дніпропетровська область  111.000000
1           Вінницька область  109.000000
18      Тернопільська область  109.000000
10     Кіровоградська область  108.000000
7          Запорізька область  106.000000
19         Харківська область  101.000000
15         Полтавська область  100.000000
22          Черкаська область   98.000000
17            Сумська область   92.000000
24       Чернігівська область   90.000000
4            Донецька область   82.000000
11          Луганська область   51.000000